services:
  - type: web
    name: chatapp-backend
    env: node
    buildCommand: cd backend && npm ci && npx prisma generate && npm run build
    startCommand: cd backend && npx prisma migrate deploy && npm run start:prod
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: REDIS_URL
        sync: false
      - key: NODE_ENV
        value: production
    autoDeploy: false

  - type: redis
    name: chatapp-redis
    ipAllowList: []

  - type: pserv
    name: chatapp-postgres
    databaseName: chatapp
    databaseUser: chatapp
    ipAllowList: []
