services:
  - type: web
    name: chatapp-backend
    env: node
    plan: free
    buildCommand: cd backend && npm ci && npx prisma generate && npm run build
    startCommand: cd backend && npx prisma migrate deploy && npm run start:prod
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chatapp-postgres
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: REDIS_URL
        fromService:
          type: redis
          name: chatapp-redis
          property: connectionString
      - key: NODE_ENV
        value: production

  - type: redis
    name: chatapp-redis
    plan: free

  - type: pserv
    name: chatapp-postgres
    plan: free
    databaseName: chatapp
    databaseUser: chatapp
