services:
  # PostgreSQL Database
  - type: pserv
    name: chatapp-db
    plan: free
    region: oregon
    databaseName: chatapp
    databaseUser: chatapp

  # Redis
  - type: redis
    name: chatapp-redis
    plan: free
    region: oregon
    maxmemoryPolicy: noeviction

  # Backend API
  - type: web
    name: chatapp-backend
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma migrate deploy && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        fromDatabase:
          name: chatapp-db
          property: connectionString
      - key: REDIS_HOST
        fromService:
          name: chatapp-redis
          type: redis
          property: host
      - key: REDIS_PORT
        fromService:
          name: chatapp-redis
          type: redis
          property: port
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /
